docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
site_name: zend-component-installer
site_description: Zend\Component\Installer
repo_url: 'https://github.com/zendframework/zend-component-installer'
copyright: 'Copyright (c) 2017-2018 <a href="http://www.zend.com/">Zend Technologies USA Inc.</a>'
extra_css:
  - zend-component-installer.css
